### ISSUE TITLE
불편한 점 남기기 부분에 enter block 요구

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_client#115]
불편한 점 남기기에 enter을 포함한 문자를 req 하면 req, res 가 안옵니다.. 엔터를 막아야해요
<img width="498" alt="Screen Shot 2021-06-05 at 9 53 44 PM" src="https://user-images.githubusercontent.com/67095821/120892313-a6019a80-c648-11eb-8ca7-7118bb551983.png">

**나중에는 엔터를 포함해도 post가 되게 하는걸로 구조를 바꾸도록 합시다**

**Comment by iseolin76** [comment]
안되는 이유를 알 수 있을까요?

**Comment by Johnjihwan** [comment]
전달될때 FE 에서 `\n` 까지 한 문자열로 보내줘야하는데 
아마 그렇게 안돼서 서버측에서는 예외로 받아드려 처리가 되는 것 같습니다.

**Comment by iseolin76** [comment]
현재 기준 
\n 즉 개행문자가 있어도 요청이 잘 보내지는 것으로 확인되었습니다.
<img width="272" alt="스크린샷 2021-06-09 오전 12 30 13" src="https://user-images.githubusercontent.com/65021545/121214234-ddc34900-c8b9-11eb-926c-9de1a8f02c84.png">

감사합니다.
