### ISSUE TITLE
실제 개선사례 enter 적용 안되는 이슈

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_client#116]
<img width="545" alt="Screen Shot 2021-06-05 at 10 07 17 PM" src="https://user-images.githubusercontent.com/67095821/120892694-80759080-c64a-11eb-90ec-39a61da7cb9d.png">

###  content 작성 부분에 enter를 포함한 string에 대하여..  
POST는 되지만 GET 부분에서 enter 적용이 안되서 나옵니다.

**Comment by Goolgae** [comment]
아마도 문자열 처리 과정에서 뭔가를 더 해줘야 하나 보네요 !! 확인했습니다.

**Comment by iseolin76** [comment]
해당 이슈는 해결하였으므로 닫겠습니다.
