### ISSUE TITLE
버튼 가운데 정렬이 안 됩니다.

### ISSUE THREAD

**Issue by Nayejun** [theMomentTeam/the_moment_client#118]
불편사항이 두 줄이상이 되어 줄바꿈이 발생할 때 블럭이 커지는데 그 때 '답변 없음' 버튼이 가운데로 이동하지 않습니다.
![Screen Shot 2021-06-07 at 4 06 16 PM](https://user-images.githubusercontent.com/67637706/120973795-5a670200-c7aa-11eb-8271-36207f784489.png)

**Comment by Goolgae** [comment]
flex 속성의 문제인것으로 보입니다.
topten element 박스의 스타일 레거시 코드에 충분히 인지하고 있습니다.

**Comment by Goolgae** [comment]
근데 이 이슈는 해결하려면 시간이 좀 걸릴듯 합니다.
@iseolin76 나중에 topten 엘리먼트 리퍼블리싱을 해야 하겠네요..

**Comment by iseolin76** [comment]
알겠습니다
