### ISSUE TITLE
반응형 오류

### ISSUE THREAD

**Issue by ImChangGyu** [theMomentTeam/the_moment_client#119]
<img width="1017" alt="스크린샷 2021-06-07 오후 4 05 58" src="https://user-images.githubusercontent.com/66630940/120973788-56d37b00-c7aa-11eb-8b84-f375089c28cf.png">
의견남기기 페이지을 줄였을때 의견들이 겹치는 현상이 발생합니다

**Comment by Goolgae** [comment]
저 경우에는 list를 삼분할 하여 렌더링하는 레거시 코드의 문제로 선택자를 남발한 과거 저의 무지한 실수입니다. 예전부터 고민하고 있던 이슈라 곧 해결할 기미가 보이는 이슈입니다. 빠른 시일내에 v1.0.1에 보여드리도록 하겠습니다.
