### ISSUE TITLE
Top 10 보러가기 페이지 이동 실패

### ISSUE THREAD

**Issue by pdlma0904** [theMomentTeam/the_moment_client#120]
![image](https://user-images.githubusercontent.com/57673815/120976496-5ab4cc80-c7ad-11eb-9dbe-1146dc04a730.png)
the_moment 페이지의 Top 10 보러가기 버튼을 눌러도 이동이 안됩니다.
확인 해보니 `많은 학생들이 공감한 불편함은 무엇일까요?`에 마우스가 포커스는 되지만 이동이 안됩니다.
마우스 포커스를 삭제하거나 그 부분을 눌러도 이동되게 만들어 주시면 감사 하겠습니다.

**Comment by Goolgae** [comment]
버튼 박스에도 마우스 호버 이벤트를 적용했네요.
호버 이벤트를 빼는 형식으로 픽스 진행하겠습니다 !!

**Comment by Goolgae** [comment]
그리고 지금 보니 윈도우 운영체제를 지니고 있는 브라우저에서는 폰트가 굉장히 안 예쁘군요..

**Comment by iseolin76** [comment]
버튼 전체를 눌러도 이동되는 로직을 추가하는 방향으로 수정하겠습니다.

제보 감사합니다!
