### ISSUE TITLE
등록 , 카운팅 bug

### ISSUE THREAD

**Issue by TeMlN** [theMomentTeam/the_moment_client#121]
<img width="732" alt="Screen Shot 2021-06-07 at 4 34 39 PM" src="https://user-images.githubusercontent.com/69895452/120977408-445b4080-c7ae-11eb-98cf-b6d1da4c67fc.png">
Comment가 29개 이상으로 작성이 되질 않고 캠페인 및 자세히 보기에도 카운팅 되지 않습니다

**Comment by Goolgae** [comment]
그건 저희 클라이언트 쪽 문제가 아니라 서버측의 idx 문제로 보입니다.
[이곳](https://github.com/theMomentTeam/the_moment_server/issues)에 이슈를 달아주시면 감사하겠습니다.
