### ISSUE TITLE
Header 반응형 오류

### ISSUE THREAD

**Issue by sanggyu0929** [theMomentTeam/the_moment_client#125]
1200px대 화면에서 헤더에 있는 메뉴 텍스트가 밀립니다. (윈도우 기준)

**Comment by Goolgae** [comment]
아마 윈도우 운영체제와 맥 os같의 폰트가 적용되는것이 달라 발생하는 이슈인것 같습니다. 빠른 시일내에 v1.0.1에서 배포토록 하겠습니다.
그리고 혹시 사진을 올려주실수 있으신가요?

**Comment by sanggyu0929** [comment]
![image](https://user-images.githubusercontent.com/53306780/120987825-ef70f780-c7b8-11eb-9966-57b172931da3.png)

**Comment by sanggyu0929** [comment]
추가로 메뉴도 안 뜨고 햄버거 메뉴도 안 뜨는 오류도 있네요.
![image](https://user-images.githubusercontent.com/53306780/120988468-905fb280-c7b9-11eb-89b3-d8bc96316584.png)
