### ISSUE TITLE
글이 길어질 경우 가독성의 문제

### ISSUE THREAD

**Issue by sunrabbit123** [theMomentTeam/the_moment_client#126]
![image](https://user-images.githubusercontent.com/64676070/120990617-b25a3480-c7bb-11eb-8c6b-98b704f0ce11.png)
다음 사진의 46번째 불편함, 25번째 불편함, 42번째 불편함을 보면 알다시피, 글이 밀림으로써 가독성이 저하됩니다.

해당사항에 대해 markdown이나 화이트필터링 방식으로 `<br>`태그와 `<b>`태그들을 도입하는것을 검토 부탁드립니다.

**Comment by sunrabbit123** [comment]
추가로 
![image](https://user-images.githubusercontent.com/64676070/120991375-868b7e80-c7bc-11eb-8edb-6aede45e6025.png)

다음과 같이 3등분하여 최신의 것 부터 보여주는 방식은 의도한 내용인가요

idx값에 asc, desc 방식의 정렬을 도입함과 동시에 위부터 차례대로 출력하는 방식이 가독성이 더욱 더 좋을 것 같다는 의견입니다

**Comment by Johnjihwan** [comment]
> 추가로
> ![image](https://user-images.githubusercontent.com/64676070/120991375-868b7e80-c7bc-11eb-8edb-6aede45e6025.png)
> 
> 다음과 같이 3등분하여 최신의 것 부터 보여주는 방식은 의도한 내용인가요
> 
> idx값에 asc, desc 방식의 정렬을 도입함과 동시에 위부터 차례대로 출력하는 방식이 가독성이 더욱 더 좋을 것 같다는 의견입니다

FE 설계 대한 답변은 아니지만, 서비스 방향성에 대한 답변드리겠습니다.
이 부분은 서비스 개발 당시 순서대로 보여주는 것 보다 랜덤으로 보여주는게 UX적으로 신선할 것 같다는 생각이였습니다.
단지 `오래된 불편함`이라고 창 맨 하단에 고정 돼 있는것 보다는 랜덤으로 표출하는 것이 더 나을 것 같다는 생각이였습니다.

**Comment by Goolgae** [comment]
### 답변드리겠습니다. @sunrabbit123 

> Q: 다음 사진의 46번째 불편함, 25번째 불편함, 42번째 불편함을 보면 알다시피, 글이 밀림으로써 가독성이 저하됩니다.

A: 저희 서비스는 간단한 글을 올리는것이 도메인에 맞다고 판단합니다. 아직 추가를 하지 못했지만 글자 제한수를 두어 글의 `length`를 조정할 예정입니다.

> Q: 다음과 같이 3등분하여 최신의 것 부터 보여주는 방식은 의도한 내용인가요

A: 저것도 마찬가지로 의도적으로 한것은 아니지만 추후에 랜덤으로 표현하는 방식이 UX적으로 독창적일것 같아 고려중입니다.
