### ISSUE TITLE
Admin 답변 달기 error

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_client#128]
![FE_400_error](https://user-images.githubusercontent.com/67095821/121110064-a3b95f00-c847-11eb-8bcd-4bd6700ec18c.png)

BE 운영 서버 api test를 해서 BE api 자체도 정상적인지 확인하겠습니다.
우선 400 에러가 뜨는걸로 봐서는 req 형식이나 client side에서 나는 오류인걸로 보입니다.

**Comment by Goolgae** [comment]
해결한 문제였지만 5월 4째주 develop -> release 에 보내던 중 코드가 유실된듯 합니다...

**Comment by Goolgae** [comment]
이런 실수를..
