### ISSUE TITLE
답변 보기와 답변 없음의 위치적 차이

### ISSUE THREAD

**Issue by sunrabbit123** [theMomentTeam/the_moment_client#138]
![image](https://user-images.githubusercontent.com/64676070/122677541-b0618e00-d21d-11eb-88d9-28c25d4ab83e.png)

해당 사진은 !()[https://www.the-moment.org/rank]의 1~2위를 스크린샷으로 남긴 사진입니다.

1위의 경우 좋아요가 3자리 수에 해당하고  
2위의 경우 좋아요가 2자리 수에 해당합니다.

이로 인해 칸이 밀리는 것으로 추정됩니다.

비슷한 사례로 6위와 7위의 차이가 있겠네요.
![image](https://user-images.githubusercontent.com/64676070/122677589-eef74880-d21d-11eb-9bae-71e2f80da6e8.png)

**Comment by sunwoo0706** [comment]
이미 존재하는 이슈입니다. v.1.0.1에 픽스한 상태로 배포하겠습니다.
