### ISSUE TITLE
top30 direct btn have an error

### ISSUE THREAD

**Issue by minhyuuk** [theMomentTeam/the_moment_client#150]
![image](https://user-images.githubusercontent.com/67806878/124436232-baa09200-ddb0-11eb-986f-16aae09512f0.png)
top30으로 개편되었는데 top10으로 되어있어요. 다음 버전 또는 핫픽스로 고쳐주세요

**Comment by sunwoo0706** [comment]
확인하였습니다.

**Comment by sunwoo0706** [comment]
#152 
현재 이슈 해결되어서 close 하도록 하겠습니다.
