### ISSUE TITLE
beta 테스트 1차 수정요구에 대한 이슈입니다.

### ISSUE THREAD

**Issue by Johnjihwan** [theMomentTeam/the_moment_client#85]
### 각 url 별 내용 수정을 요구합니다.

1. 메인페이지
```
-기존
https://the-moment.org/Leave_opinion
-변경
https://the-moment.org/the_moment
```

2. top10
```
-기존
https://the-moment.org/topten
-변경
https://the-moment.org/rank
```

3. 추가적으로 로고를 눌렀을때, 아래로 redirect 설정을 추가해주세요.
```
https://the-moment.org/the_moment
```

### title 에 관한 수정을 요구합니다.
- 기존: The Moment
- 변경: the_moment

### 반응형 수정을 요구합니다.
참고
```
https://toss.im/every-moment
```

**Comment by iseolin76** [comment]
url 내용 수정 및 title 수정 완료했습니다.
반응형 수정 후 다시 알려드리겠습니다.

**Comment by Johnjihwan** [comment]
네네 지금 수정된 디자인 시안으로 마진 조정 부탁드립니다 :) 최대한요 !
